@host=http://localhost:5267

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZDU2YzYzMS01N2Y1LTQxZTktOGE2MS03NTZiZGZkMGE5ODQiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiY2ZlMTZjNGQtNmQ5OS00YTFjLThlYjQtOWZlZDMxZTVjODRhIiwiZXhwIjoxNjgyNDUxOTMxLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMSJ9.gCZvm-fz_7j1MRE0-vEnm9z9Eb8gOLIw1t4fmTRDYuQ

